---
title: "Case Study 09"
author: Joe Benz
date: November 2, 2021
output: github_document
---
 Load Data and Relevant Packages
```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
data(world)
data(us_states)
```

```{r}
# Download zipped data from noaa with storm track information
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir)
list.files(tdir)

storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))
```

```{r}
storms <- storm_data%>%
  filter(SEASON > 1949)%>% #Only use data from 1950 to present
  mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x))%>% #Fix NA values
  mutate(decade=(floor(year/10)*10)) #create decade column

region <- st_bbox(storms)

ggplot()+
  geom_sf(data = world, inherit.aes = F)+
  facet_wrap(~decade)+
  stat_bin2d(data=storms, aes(y=st_coordinates(storms)[,2], x=st_coordinates(storms)[,1]),bins=100)+
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000))+
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)])
  
```

```{r}
states <- st_transform(us_states, crs = 4326)%>% #Change projection to match storms
  select(state = NAME)

storm_states <- st_join(storms, states, join = st_intersects,left = F)%>%
  group_by(state)%>%
  summarize(storms=length(unique(NAME)))%>%
  arrange(desc(storms))%>%
  slice(1:5)

top5 <- select(storm_states, -last_col())
#make table
top5
```

 