---
title: "Case Study 11"
author: Joe Benz
date: November 18, 2021
output: github_document
---
 Load Packages
```{r}
library(tidyverse)
library(spData)
library(sf)

## New Packages
library(mapview) # new package that makes easy leaflet maps
library(foreach)
library(doParallel)
registerDoParallel(4)
getDoParWorkers() # check registered cores
```

Census API Key
```{r}
library(tidycensus)
census_api_key("4fd08123c224ef332b370b4182ef40e87396a508", install = TRUE, overwrite = TRUE)
```

Download Block-Level Data
```{r}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)

erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=T) 

```
 Crop to County
```{r}
county <- st_crop(erie, xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)
```
 Create For Loop
```{r}
dot_map <- foreach(r=unique(county$variable),.combine='rbind') %dopar% 
  {   filter(buffalo, variable==r) %>%
        st_sample(size=.$value) %>%
        st_as_sf() %>%
        mutate(variable=r)
  }
```
 Plot
```{r}
mapview(dot_map, zcol = "variable", cex = 0.01, alpha = 0)
```