---
title: "Case Study 05"
author: Joseph Benz
date: October 5, 2020
output: github_document
---
 
library(spData)
library(sf)
library(tidyverse)
library(units)  
#this one is optional, but can help with unit conversions.

#load 'world' data from spData package
data(world)  
# load 'states' boundaries from spData package
data(us_states)
# plot(world[1])  #plot if desired
# plot(us_states[1]) #plot if desired

#Transform the world dataset and filter out canada, also set buffer of 10000m
canada_buffer = world %>%
  st_transform(crs="+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0        +ellps=GRS80 +datum=NAD83 +units=m +no_defs") %>%
  filter(name_long=="Canada")%>%
  st_buffer(dist=10000)
  
#Do the same for us_states and NY
ny_map = us_states %>%
  sf::st_transform(crs="+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0        +ellps=GRS80 +datum=NAD83 +units=m +no_defs") %>%
  filter(NAME=="New York")

#Create an object representing overlap  
intersect = st_intersection(canada_buffer, ny_map)
  
#Plot NY and the overlap  
ggplot()+ 
  geom_sf(data=ny_map)+
  geom_sf(data=intersect, col="red", fill="red")

#Calculate area
intersect_area = st_area(intersect)%>%
  set_units(km^2)
  

  
  